
# Generated by Django 5.0.2 on 2024-03-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_audio_file_book_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
