
# Generated by Django 5.0.2 on 2024-03-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_category_created_at_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Fairy Tales', 'Fairy Tales'), ('Adventure', 'Adventure'), ('Animals', 'Animals'), ('Fantasy', 'Fantasy'), ('Educational', 'Educational'), ('Bedtime Stories', 'Bedtime Stories')], max_length=100),
        ),
    ]