
# Generated by Django 5.0.2 on 2024-03-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_category_created_at_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='books',
            field=models.ManyToManyField(related_name='categories', to='api.book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]